
server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 使用Alibaba Druid连接池
    druid:  # Druid连接池的配置项
      url: jdbc:mysql:///school  # 数据库URL，连接到名为school的数据库
      username: root  # 数据库用户名
      password: '123456'  # 数据库密码
      driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL驱动类
  application:
    name: demo
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
